# Generated by Django 5.0.2 on 2024-02-29 12:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_product', models.CharField(max_length=255)),
                ('start_date_time_product', models.DateTimeField()),
                ('price_product', models.DecimalField(decimal_places=2, max_digits=2)),
                ('author_creathor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('neme_lesson', models.CharField(max_length=255)),
                ('video_link', models.URLField()),
                ('lesson_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_product', to='project.product')),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_count_users', models.PositiveBigIntegerField()),
                ('max_count_users', models.PositiveBigIntegerField()),
                ('group_members', models.ManyToManyField(related_name='group_members', to=settings.AUTH_USER_MODEL)),
                ('group_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_product', to='project.product')),
            ],
        ),
        migrations.CreateModel(
            name='AcessProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.product')),
            ],
        ),
    ]
